Changed the pulse count and event duraction script.
graphnet-team/analyses pull request #8
Opened 2022-10-13 10:12 UTC by Peterandresen12

2022-10-13 10:57 UTC, MortenHolmRep reviewed
Add bit type files to .gitignore

2022-10-13 11:44 UTC, asogaard commented
What are these binary files you're trying to ignore? 🙂

2022-10-13 12:15 UTC, MortenHolmRep commented
> What are these binary files you're trying to ignore? 🙂

The plotting script took some time to run, due to fetching via SQLite query. So peter wanted to download the numpy array for a quicker sampling of the dataset.
So in essence, the binary files contain IceCube data, which should not be on here.

2022-10-13 14:59 UTC, asogaard commented
> > What are these binary files you're trying to ignore? 🙂
> 
> The plotting script took some time to run, due to fetching via SQLite query. So peter wanted to download the numpy array for a quicker sampling of the dataset. Pickle generate binary files when it stores data.
> So in essence, the binary files contain IceCube data, which should not be on here.

Wouldn't it make sense, then, to save them as .npy or .npz files, and just put these extensions in the gitignore-file? I'm a little worried about excluding everything and then "unexcluding" directories and files with extensions.

2022-10-18 11:30 UTC, Peterandresen12 commented
Yes, makes sense, I have changed it such that git ignores .pickle files instead :-)

2022-10-18 11:33 UTC, MortenHolmRep requested changes
wandb stuff shouldn't be included

2022-10-18 12:51 UTC, MortenHolmRep commented on .gitignore
> +wandb/
try `wandb/*`

2022-10-22 19:11 UTC, asogaard approved these changes
Hi @Peterandresen12,

I am fine with the changes made to the common files. I would suggest you remove the wandb file included (`moon_pointing_analysis/modelling/wandb/wandb/latest-run`) before merging, though, but since it only affects your own area, that's entirely up to you. :)

2022-10-25 11:11 UTC, Peterandresen12 commented on .gitignore
> +wandb/
Fixed

2022-10-26 10:27 UTC, MortenHolmRep approved these changes
let's gooooo

2022-10-26 10:28 UTC, merged